spring:
    redis:
        database: 1
        port: 6379
        host: redis
        password:
        jedis:
          pool:
            max-active: 8
            max-idle: 8
            max-wait: 2000ms
            min-idle: 2
#奖池配置参数
prizePool:
    prizeSize: 7
    specialAndFirstLine: 3
    firstAndSecondLine: 0
    secondAndThirdLine: 0
server:
  port: 80